---
# COPY this file to secrets.yml
development:
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: dwufw1334ADCRn71dsd#$%^^^&&*()""bac34jfs4E20
  MSG_KEY: <use `rake new_key:msg`>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP
  GET_USER_INFO: https://oauth2.googleapis.com/tokeninfo?id_token=

test:
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: dwufw1334ADCRn71dsd#$%^^^&&*()""bac34jfs4E20
  MSG_KEY: <use `rake new_key:msg`>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP
  GET_USER_INFO: https://oauth2.googleapis.com/tokeninfo?id_token=

production:
  DATABASE_URL: <set to production DB>
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  MSG_KEY: <use `rake new_key:msg`>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTPS
  GET_USER_INFO: https://oauth2.googleapis.com/tokeninfo?id_token=
